# Height prediction using Decision Tree

# #Import dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Load the dataset

In [4]:
dataset=pd.read_csv("C:\\Users\\91951\\Downloads\\15_heightpredictionfromage_decisiontree\\dataset.csv")

In [5]:
dataset

Age  Height
0    10     138
1    11     138
2    12     138
3    13     139
4    14     139
..  ...     ...
66   76     204
67   77     205
68   78     206
69   79     207
70   80     208

[71 rows x 2 columns]

In [6]:
## Summarize Dataset

In [7]:
print(dataset.shape)

(71, 2)


In [9]:
print(dataset.head(5))

   Age  Height
0   10     138
1   11     138
2   12     138
3   13     139
4   14     139


In [10]:
print(dataset.tail(5))

    Age  Height
66   76     204
67   77     205
68   78     206
69   79     207
70   80     208


In [11]:
print(dataset.describe())

             Age      Height
count  71.000000   71.000000
mean   45.000000  160.873239
std    20.639767   20.842902
min    10.000000  138.000000
25%    27.500000  143.500000
50%    45.000000  155.000000
75%    62.500000  171.500000
max    80.000000  208.000000


In [12]:
## Segregate Dataset into Input(X) and Output (Y)

In [19]:
x=dataset.iloc[:,:-1].values
x

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64],
       [65],
       [66],
       [67],
       [68],
       [69],
       [70],
       [71],
       [72],
       [73],
       [74],
       [75],
       [76],
       [77],
       [78],
       [79],
       [80]], dtype=int64)

In [24]:
y=dataset.iloc[:,-1].values
y

array([138, 138, 138, 139, 139, 139, 140, 140, 140, 141, 141, 141, 142,
       142, 142, 143, 143, 143, 144, 144, 145, 145, 146, 146, 147, 147,
       148, 148, 149, 149, 150, 150, 151, 152, 153, 155, 156, 157, 158,
       159, 160, 161, 162, 163, 164, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 175, 178, 180, 183, 185, 188, 190, 193, 195, 199,
       203, 204, 205, 206, 207, 208], dtype=int64)

In [25]:
## Splitting Dataset for Testing our model

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)

In [28]:
## Training Dataset using Decision Tree

In [31]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(x_train,y_train)

DecisionTreeRegressor()

In [32]:
## Visualizing Graph

In [41]:
x_val=np.arange(min(x_train),max(x_train),0.01)
x_val=x_val.reshape(len(x_val),1)
plt.scatter(x_train,y_train,color='blue')
plt.plot(x_val,model.predict(x_val),color='red')
plt.title("Height prediction using DecisionTree")
plt.xlabel("Age")
plt.ylabel("Height")
plt.figure()
plt.show()

<Figure size 432x288 with 0 Axes>

In [38]:
## Prediction for all test data for validation

In [39]:
print(x_test)

[[36]
 [37]
 [58]
 [32]
 [40]
 [61]
 [17]
 [69]
 [44]
 [80]
 [66]
 [38]
 [41]
 [52]
 [43]]


In [43]:
y_pred = model.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print("Root Mean Squared Error :",rmse)
r2score=r2_score(y_test,y_pred)
print("R2_Score",r2score*100)

Root Mean Squared Error : 1.3416407864998738
R2_Score 99.42815994578109
